# Generated by Django 5.2.7 on 2025-10-05 09:46

import django.db.models.deletion
import utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='shop slug')),
                ('name', models.CharField(max_length=100, validators=[utils.validators.not_only_whitespace], verbose_name='shop name')),
                ('about', models.TextField(blank=True, max_length=1000, null=True, validators=[utils.validators.not_only_whitespace], verbose_name='about shop')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='shop_profiles', verbose_name='shop profile photo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='shop verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='shop activity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='shop created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='shop updated at')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_media', verbose_name='images of shop')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt text for image')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
