# Generated by Django 5.2.7 on 2025-10-05 10:58

import django.core.validators
import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True, validators=[utils.validators.not_only_whitespace], verbose_name='About shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Shop created at'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Shop activity'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Shop verified'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, validators=[utils.validators.not_only_whitespace], verbose_name='Shop name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='shop_profiles', verbose_name='Shop profile photo'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Shop slug'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Shop updated at'),
        ),
        migrations.AlterField(
            model_name='shopmedia',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text for image'),
        ),
        migrations.AlterField(
            model_name='shopmedia',
            name='image',
            field=models.ImageField(upload_to='shop_media', verbose_name='Images of shop'),
        ),
        migrations.AlterField(
            model_name='shopmedia',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='Shop'),
        ),
        migrations.CreateModel(
            name='ShopBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_branch_name', models.CharField(max_length=100, validators=[utils.validators.not_only_whitespace], verbose_name='Shop branch name')),
                ('about', models.TextField(blank=True, max_length=2000, null=True, verbose_name='About shop branch')),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Shop branch phone number')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='Shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=200, null=True, validators=[utils.validators.not_only_whitespace], verbose_name='Comment text')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Comment rating(1-5)')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop', verbose_name='Shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ShopSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(max_length=50, verbose_name='Media name')),
                ('media_url', models.URLField(verbose_name='Media url')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
