# Generated by Django 5.2.7 on 2025-10-06 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_about_alter_shop_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbranch',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Shop branch slug'),
        ),
        migrations.AddField(
            model_name='shopcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Comment created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Comment updated at'),
        ),
        migrations.AlterField(
            model_name='shopbranch',
            name='phone_number',
            field=models.CharField(blank=True, null=True, verbose_name='Shop branch phone number'),
        ),
    ]
