# Generated by Django 5.2.7 on 2025-10-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shopbranch_slug_shopcomment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', max_length=80, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
