# Generated by Django 5.2.7 on 2025-10-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbranch',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', max_length=80, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
