# Generated by Django 5.2.7 on 2025-10-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_shopbranch_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopbranch',
            old_name='shop_branch_name',
            new_name='name',
        ),
    ]
